[versions]
accompanistPermissions = "0.37.3"
kotlin = "2.3.0"
kotlinOnetimepassword = "1.0.0"
ksp = "2.3.4"
lifecycleViewmodelNav3 = "2.10.0"
nav3Core = "1.0.0"
room = "2.8.4"
skie = "0.10.9"
sonarqube = "7.2.3.7755"
sqlite = "2.6.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
kotlin-onetimepassword = { module = "com.marcelkliemannel:kotlin-onetimepassword", version.ref = "kotlinOnetimepassword" }

infomaniak-core-auth = { module = "com.infomaniak.core:Auth" }
infomaniak-core-common = { module = "com.infomaniak.core:Common" }
infomaniak-core-crossapplogin-back = { module = "com.infomaniak.core:CrossAppLogin.Back" }
infomaniak-core-crossapplogin-front = { module = "com.infomaniak.core:CrossAppLogin.Front" }
infomaniak-core-onboarding = { module = "com.infomaniak.core:Onboarding" }
infomaniak-core-network = { module = "com.infomaniak.core:Network" }
infomaniak-core-sentry = { module = "com.infomaniak.core:Sentry" }
infomaniak-core-ui-compose-basics = { module = "com.infomaniak.core:Ui.Compose.Basics" }
infomaniak-core-ui-compose-basicbutton = { module = "com.infomaniak.core:Ui.Compose.BasicButton" }
infomaniak-core-ui-compose-bottomstickybuttonscaffolds = { module = "com.infomaniak.core:Ui.Compose.BottomStickyButtonScaffolds" }
infomaniak-core-ui-compose-margin = { module = "com.infomaniak.core:Ui.Compose.Margin" }
infomaniak-core-ui-compose-preview = { module = "com.infomaniak.core:Ui.Compose.Preview" }
infomaniak-core-ui-compose-theme = { module = "com.infomaniak.core:Ui.Compose.Theme" }

[plugins]
androidx-room = { id = "androidx.room", version.ref = "room" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
