[versions]
accompanistPermissions = "0.37.3"
authenticatorCore = "1.0.0"
kotlin = "2.3.21"
sonarqube = "7.3.1.8318"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
infomaniak-multiplatform-authenticator-core-submodule = { module = "com.infomaniak.multiplaform-authenticator:multiplatform-authenticator" }
infomaniak-multiplatform-authenticator-core = { group = "com.infomaniak.multiplatform_authenticator", name = "AuthenticatorCore", version.ref = "authenticatorCore" }
play-services-block-store = { module = "com.google.android.gms:play-services-auth-blockstore", version = "16.4.0" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
