name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 2 # Fetches the merge commit and its two parents

      - id: check
        shell: bash
        run: |
          # HEAD^1 = Base Branch (e.g., main)
          # HEAD^2 = Your PR Branch
          # Filter out .md files and .github directory
          CHANGES=$(git diff --name-only HEAD^1 HEAD^2 | grep -vE '^(\.github/|.*\.md$)' || true)
          
          if [ -z "$CHANGES" ]; then
            echo "No relevant changes found. Skipping tests."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "Relevant changes detected."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi
  lint:
    needs: check-changes
    if: needs.check-changes.outputs.should_run == 'true'
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Run lint
        uses: infomaniak/.github/.github/workflows/android-lint.yml@v2

  instrumentation-tests:
    needs: check-changes
      # This job ONLY runs if the previous job found relevant files
    if: needs.check-changes.outputs.should_run == 'true'
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.token }}
          submodules: recursive

      # Setup Gradle and Run tests
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean gradle cache
        run: ./gradlew clean

      # Making sure the app compiles
      - name: Build app
        run: ./gradlew assembleDebug

      - name: Run unit tests and analyze with sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew testStandardDebugUnitTest testFdroidDebugUnitTest sonar --info --stacktrace
