name: Android CI

on:
  pull_request:
    paths-ignore: [.github/**, "**.md"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation-tests:
    if: github.event.pull_request.draft == false
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.token }}
          submodules: recursive

      # Setup Gradle and Run tests
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean gradle cache
        run: ./gradlew clean

      # Making sure the app compiles
      - name: Build app
        run: ./gradlew assembleDebug

      # Runs the lint while waiting for the `build` task to run them automatically
      - name: Run lint
        run: ./gradlew lint

      - name: Run unit tests and analyze with sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew testStandardDebugUnitTest testFdroidDebugUnitTest sonar --info --stacktrace
