name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 2 # Fetches the merge commit and its two parents

      - id: check
        shell: bash
        run: |
          # HEAD^1 = Base Branch (e.g., main)
          # HEAD^2 = Your PR Branch
          # Keep changes in multiplatform-lib or Core submodule updates
          CHANGES=$(git diff --name-only HEAD^1 HEAD^2 | grep -E '^(multiplatform-lib/|Core($|/))' || true)
          
          if [ -z "$CHANGES" ]; then
            echo "No relevant changes found. Skipping tests."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "Relevant changes detected."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  build-apple-bundle:
    name: Verify generation of XCframework
    needs: check-changes
      # This job ONLY runs if the previous job found relevant files
    if: needs.check-changes.outputs.should_run == 'true'
    runs-on: [ self-hosted, Android ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.token }}
          submodules: recursive

      # Setup Gradle and Run tests
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean gradle cache
        run: ./gradlew clean

      # Making sure XCFramework build
      - name: Build XCFramework
        run: ./gradlew :multiplatform-lib:assembleCoreAuthenticatorXCFramework
